# Generated by Django 4.1.1 on 2022-10-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0002_user_details_email_user_details_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_mail", models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name="User_Details",
        ),
    ]
