# Generated by Django 4.1.1 on 2022-10-03 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0003_emails_delete_user_details"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Emails",
            new_name="email",
        ),
    ]
